apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: personopplysninger-api-legacy-alert
  namespace: min-side
  labels:
    team: min-side
spec:
  groups:
    - name: personopplysninger-api-legacy-alert
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="personopplysninger-api", namespace="personbruker"} == 0
          for: 2m
          annotations:
            summary: "App personopplysninger-api er nede"
            action: "Sjekk logger/events i kubectl"
          labels:
            namespace: min-side
            severity: danger
        - alert: høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(log_messages_errors{app="personopplysninger-api",namespace="personbruker",level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(log_messages_total{namespace="personbruker", app="personopplysninger-api"}[3m]))) > 10
          for: 3m
          annotations:
            summary: "App personopplysninger-api har høy feilrate i logger"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            namespace: min-side
            severity: warning
        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^5\\d\\d", namespace="personbruker", app="personopplysninger-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="personopplysninger-api"}[3m])))) > 1
          for: 3m
          annotations:
            summary: "App personopplysninger-api returnerer en høy andel 5xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            namespace: min-side
            severity: danger
        - alert: Høy andel HTTP klientfeil (4xx responser)
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^4\\d\\d", namespace="personbruker", app="personopplysninger-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="personopplysninger-api"}[3m])))) > 10
          for: 3m
          annotations:
            summary: "App personopplysninger-api returnerer en høy andel 4xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            namespace: min-side
            severity: warning
        - alert: Test alert til min side fra personopplysninger-api
          expr: vector(1)
          for: 15m
          annotations:
            summary: "Test alert fra personopplysninger-api til Min side"
            action: "test "
          labels:
            namespace: min-side
            severity: info
        - alert: Test alert til min side fra personopplysninger-api med ekte query.
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^2\\d\\d", namespace="personbruker", app="personopplysninger-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="personopplysninger-api"}[3m])))) > 10
          for: 15m
          annotations:
            summary: "Test alert fra personopplysninger-api til Min side"
            action: "test "
          labels:
            namespace: min-side
            severity: warning