apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: personopplysninger-api-legacy-alert
  namespace: min-side
  labels:
    team: min-side
spec:
  groups:
    - name: min-side-personopplysninger-api-alert
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="personopplysninger-api", namespace="personbruker"} == 0
          for: 2m
          annotations:
            summary: "App personopplysninger-api er nede"
            action: "Sjekk logger/events i kubectl"
          labels:
            namespace: min-side
            severity: danger
        - alert: høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(log_messages_errors{app="personopplysninger-api",namespace="personbruker",level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(log_messages_total{namespace="personbruker", app="personopplysninger-api"}[3m]))) > 10
          for: 3m
          annotations:
            summary: "App personopplysninger-api har høy feilrate i logger"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            namespace: min-side
            severity: warning
        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^5\\d\\d", namespace="personbruker", app="personopplysninger-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="personopplysninger-api"}[3m])))) > 1
          for: 3m
          annotations:
            summary: "App personopplysninger-api returnerer en høy andel 5xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            namespace: min-side
            severity: danger
        - alert: Høy andel HTTP klientfeil (4xx responser)
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^4\\d\\d", namespace="personbruker", app="personopplysninger-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="personopplysninger-api"}[3m])))) > 10
          for: 3m
          annotations:
            summary: "App personopplysninger-api returnerer en høy andel 4xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            namespace: min-side
            severity: warning
    - name: min-side-arbeidsforhold-api-alert
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="arbeidsforhold-api", namespace="personbruker"} == 0
          for: 2m
          annotations:
            summary: "App arbeidsforhold-api er nede"
            action: "Sjekk logger/events i kubectl"
          labels:
            namespace: min-side
            severity: danger
        - alert: høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(log_messages_errors{app="arbeidsforhold-api", namespace="personbruker", level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(log_messages_total{app="arbeidsforhold-api"}[3m]))) > 10
          for: 3m
          annotations:
            namespace: min-side
            summary: "App arbeidsforhold-api har høy feilrate i logger"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            namespace: min-side
            severity: warning
        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^5\\d\\d", namespace="personbruker", app="arbeidsforhold-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="arbeidsforhold-api"}[3m])))) > 1
          for: 3m
          annotations:
            summary: "App arbeidsforhold-api returnerer en høy andel 5xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            namespace: min-side
            severity: danger
        - alert: Høy andel HTTP klientfeil (4xx responser)
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^4\\d\\d", namespace="personbruker", app="arbeidsforhold-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="arbeidsforhold-api"}[3m])))) > 10
          for: 3m
          annotations:
            summary: "App arbeidsforhold-api returnerer en høy andel 4xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            severity: warning
            namespace: min-side
    - name: min-side-dsop-api-alert
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="dsop-api", namespace="personbruker"} == 0
          for: 2m
          annotations:
            summary: "App dsop-api er nede"
            action: "Sjekk logger/events i kubectl"
          labels:
            severity: danger
            namespace: min-side
        - alert: høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(log_messages_errors{app="dsop-api", namespace="personbruker", level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(log_messages_total{app="dsop-api", namespace="personbruker"}[3m]))) > 10
          for: 3m
          annotations:
            summary: "App dsop-api har høy feilrate i logger"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            severity: warning
            namespace: min-side
        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^5\\d\\d", namespace="personbruker", app="dsop-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="dsop-api"}[3m])))) > 1
          for: 3m
          annotations:
            summary: "App dsop-api returnerer en høy andel 5xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            severity: danger
            namespace: min-side
        - alert: Høy andel HTTP klientfeil (4xx responser)
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^4\\d\\d", namespace="personbruker", app="dsop-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="dsop-api"}[3m])))) > 10
          for: 3m
          annotations:
            summary: "App dsop-api returnerer en høy andel 4xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            severity: warning
            namespace: min-side
        - alert: Test alert
          expr: (100 * (sum by (backend) (rate(ktor_http_server_requests_seconds_count {status=~"^2\\d\\d", namespace="personbruker", app="dsop-api"}[3m])) / sum by (backend) (rate(ktor_http_server_requests_seconds_count {namespace="personbruker", app="dsop-api"}[3m])))) > 1
          for: 5m
          annotations:
            summary: "Test alert knyttet til dsop-api"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            severity: warning
            namespace: min-side